### ISSUE TITLE
Header names case sensitivity

### ISSUE THREAD

**Issue by pboguslawski** [swaggest/rest#119]
**Describe the bug**

According to

https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

HTTP header names should be compared in a case-insensitive fashion.

With example input header definition

```
HeaderSecFetchSite string `header:"sec-fetch-site" required:"true"`
```

request with

```
Sec-Fetch-Site: same-origin
```
throws request validation failure with

```  
"header:sec-fetch-site": [
      "missing value"
    ]
```

**Expected behavior**
Requests with any of below should be passed:

```
sec-fetch-site: same-origin
Sec-Fetch-Site: same-origin
sEc-fEtCh-sitE: same-origin
```

**Comment by vearutop** [comment]
Good catch, this can be fixed.

Meanwhile, a workaround is to use canonical names:
```
HeaderSecFetchSite string `header:"Sec-Fetch-Site" required:"true"`
```
