### ISSUE TITLE
Wrong http status assigned to status.FailedPrecondition

### ISSUE THREAD

**Issue by pboguslawski** [swaggest/rest#146]
**Describe the bug**
`status.InvalidArgument` and `status.FailedPrecondition` are different statuses but are mapped to the same `http.StatusBadRequest`:

https://github.com/swaggest/rest/blob/master/error.go#L130
https://github.com/swaggest/usecase/blob/master/status/status.go#L97

**Expected behavior**
`status.FailedPrecondition`  should be mapped to `http.StatusPreconditionFailed`.

**Additional context**
Related: #145

**Comment by vearutop** [comment]
Interesting, original source of mapping is https://github.com/googleapis/googleapis/blob/f36c65081b19e0758ef5696feca27c7dcee5475e/google/rpc/code.proto#L127, I wonder was it a mistake in google repo or deliberate decision.

**Comment by pboguslawski** [comment]
Seems that:
- precondition failure in googleapis means [something different](https://github.com/googleapis/googleapis/blob/f36c65081b19e0758ef5696feca27c7dcee5475e/google/rpc/code.proto#L121) than [precondition failure in HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412),
- [`FAILED_PRECONDITION` description in googleapis](https://github.com/googleapis/googleapis/blob/f36c65081b19e0758ef5696feca27c7dcee5475e/google/rpc/code.proto#L121) does not match mapped HTTP status code 400 which [means client side problem](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400).

Consider replacing 400->412 for `status.FailedPrecondition` to allow API clients to distinguish failed preconditions from bad client requests (i.e. invalid request).

**Comment by pboguslawski** [comment]
After this mod, when 304 is added to possible error responses with...
```
u.SetExpectedErrors(status.Internal, rest.HTTPCodeAsError(http.StatusNotModified))
```
...openapi.json contains non-empty body for 304 but [should not](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5).
