### ISSUE TITLE
Data Schema's not showing on swagger docs site

### ISSUE THREAD

**Issue by shortwavedave** [swaggest/rest#171]
**Describe the bug**
Data Schema's not showing on swagger docs site. Usually the schema is near the bottom. The json schema looks correct
![image](https://github.com/swaggest/rest/assets/22798574/8960a75f-5583-4a07-9412-0d4ffd1eb6f8)

**To Reproduce**
```
git clone https://github.com/swaggest/rest.git
cd /home/david/src/swaggest_ex/_examples/advanced-generic-openapi31
go get ./..
go run .
```

**Expected behavior**
At the bottom of the docs site there should be a section for schema

**Comment by vearutop** [comment]
This is a default behavior, defined in 
```
		"defaultModelsExpandDepth": "-1", // Hides schemas, override with value "1" in Config.SettingsUI to show schemas.
```
https://github.com/swaggest/swgui/blob/v1.7.2/internal/index.tpl.go#L29

You can disable it with custom settings for `swgui`.

```go
	// Swagger UI endpoint at /docs.
	s.Docs("/docs", func(title, schemaURL, basePath string) http.Handler {
		return swguiv5.NewHandlerWithConfig(swgui.Config{
			Title:       title,
			SwaggerJSON: schemaURL,
			BasePath:    basePath,
			SettingsUI: map[string]string{
				"defaultModelsExpandDepth": "1",
			},
		})
	})
```
instead of
```go
	// Swagger UI endpoint at /docs.
	s.Docs("/docs", swgui.New)
```

**Comment by shortwavedave** [comment]
thank you!
