### ISSUE TITLE
How to generate openapi.json file only?

### ISSUE THREAD

**Issue by futugyou** [swaggest/rest#189]
How to generate openapi.json file without using http.ListenAndServe to start the service.
I just want to use 'go run .' to generate an openapi.json file, not start a http service.

**Comment by vearutop** [comment]
You can do it with a function like this.

```go
func DumpOpenAPISpec(fn string, s *web.Service) error {
	j, err := json.Marshal(s.OpenAPISchema())
	if err != nil {
		return err
	}

	return os.WriteFile(fn, j, 0600)
}
```
