### ISSUE TITLE
Middlewares not working?

### ISSUE THREAD

**Issue by Olived-fr** [swaggest/rest#62]
Hi,

I started to use this module in a project but I can't get most of the middlewares to work with the chi wrapper.

When I use the default chi router it works without problem (e.g with CORS and StipSlashes middlewares):

```go

r := chi.NewRouter()
r.Use(
middleware.StripSlashes,
cors.Handler(cors.Options{
			AllowedOrigins:   "*",
			AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
			AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
			AllowCredentials: false,
			MaxAge:           300,
		})
)
```

But with the wrapper it does not, as I am getting CORSed on preflight requests and end slashes are not stripped:

```go
r :=  chirouter.NewWrapper(chi.NewRouter())
r.Use(...) //Same as above
```

Do you have any idea why?

**Comment by Olived-fr** [comment]
Just to complete, if I put the said middlewares on the chi router (not the wrapper) and then pass the router to the wrapper, it works : 

```go
r := chi.NewRouter()
r.Use(
  middleware.StripSlashes,
  cors.Handler(cors.Options{
			AllowedOrigins:   "*",
			AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
			AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
			AllowCredentials: false,
			MaxAge:           300,
		})
)
s := chirouter.NewWrapper(r)
s.Use(...) // Required middlewares
``

**Comment by vearutop** [comment]
Thank you for raising this issue, there seem to be indeed behavior discrepancy in how wrapper works with middlewares that affect routing (`middleware.StripSlashes` is the one). I'll check in more detail some time soon.

**Comment by vearutop** [comment]
Please try #64 with 
```
go get -u github.com/swaggest/rest@pre-route-mw
```
and let me know if it works as expected or not.

**Comment by Olived-fr** [comment]
It works perfectly, thanks!

**Comment by vearutop** [comment]
`v0.2.23` tagged.
