### ISSUE TITLE
How to customise ValidatorMiddleware's error response

### ISSUE THREAD

**Issue by marianogappa** [swaggest/rest#67]
My API spec defines that error responses must have a certain shape, which doesn't match the one that `validatorFactory := jsonschema.NewFactory(apiSchema, apiSchema)` provides.

Is there a way to customise this?

**Comment by vearutop** [comment]
Error responses can be controlled with [`rest.HandlerTrait.MakeErrResp`](https://pkg.go.dev/github.com/swaggest/rest#HandlerTrait), it affects both validation and usecase errors.

I've added a sample middleware to advanced example, please check.
https://github.com/swaggest/rest/blob/master/_examples/advanced/router.go#L31-L46
```go
		// Example middleware to setup custom error responses.
		func(handler http.Handler) http.Handler {
			var h *nethttp.Handler
			if nethttp.HandlerAs(handler, &h) {
				h.MakeErrResp = func(ctx context.Context, err error) (int, interface{}) {
					code, er := rest.Err(err)

					return code, customErr{
						Message: er.ErrorText,
						Details: er.Context,
					}
				}
			}

			return handler
		},
```

**Comment by marianogappa** [comment]
Hey, thank you for this! I didn't want to reply until I had a chance to try it. It works perfectly 👍 Thank you.
