### ISSUE TITLE
Setting additionalProperties=false in all validations

### ISSUE THREAD

**Issue by marianogappa** [swaggest/rest#68]
It's a very common issue that someone might have a typo on an optional API endpoint's `query`/`json body object property`/`url-encoded form field`, and since it doesn't match the correct one, it's ignored but doesn't necessarily need to fail in a noticeable way, therefore causing a silent error.

How can I set this?

I have these additional questions regarding validation:

- In general, it's not clear to me how to set a validation except when it's a tag on a struct field (e.g. in this case this validation is not bound to a field).
- Within struct fields, how to set a format validation when the field is a list or a map, e.g. how to define that each element on a slice must be an enum of certain strings.

**Comment by vearutop** [comment]
Thank you for raising this question, I agree this is an important topic.

Currently a way to configure structure-level schema constraints is to implement a jsonschema interface on that structure: https://github.com/swaggest/jsonschema-go#implementing-interfaces-on-a-type.

> [Preparer](https://pkg.go.dev/github.com/swaggest/jsonschema-go#Preparer) allows to change generated JSON Schema.
[Exposer](https://pkg.go.dev/github.com/swaggest/jsonschema-go#Exposer) overrides generated JSON Schema.
[RawExposer](https://pkg.go.dev/github.com/swaggest/jsonschema-go/jsonschema.RawExposer) overrides generated JSON Schema.

However, now I think these methods are not always convenient, and with small structures it can be annoying to implement `Preparer` just to set `additionalProperties: false`.

I think we can leverage unnamed fields to supply constraints for the structure itself (not only for its property).
Please check https://github.com/swaggest/jsonschema-go/pull/40, does this approach make sense in your case?

> Within struct fields, how to set a format validation when the field is a list or a map, e.g. how to define that each element on a slice must be an enum of certain strings.

In this case I suggest to use named types for constrained values and implement suitable [jsonschema interface](https://github.com/swaggest/jsonschema-go#implementing-interfaces-on-a-type) on it.

For example with enum:
```go
type Weekday string

func (w Weekday) Enum() []interface{} {
  return []interface{}{"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}
}

var myMap map[int]Weekday
var myList []Weekday
```

**Comment by vearutop** [comment]
@marianogappa please also check https://github.com/swaggest/rest/pull/70 for another approach to impose global `additionalProperties: false` on all schemas. I do not recommend to use such blanket solution, as it may turn out being too implicit, but I think it is good to know.

**Comment by marianogappa** [comment]
@vearutop Hey, thanks for working on this!

Regarding both new solutions (i.e. setting additionalProperties via unnamed struct fields and via InterceptType), are you sure they actually work?

I thought it might be an issue with my code, or the version of swaggest/jsonschema-go I had, etc, but then I started a project from scratch with the code from the bottom of swaggest's README, made sure it worked, and then I added the unnamed tag first, and then the `InterceptType` code, and I cannot get it to fail validation adding extra query/body params.

<img width="987" alt="Screenshot 2022-04-13 at 17 35 40" src="https://user-images.githubusercontent.com/1078546/163228679-ebdb2069-7e48-4245-8ca0-176f5e5b92b7.png">
<img width="1238" alt="Screenshot 2022-04-13 at 17 35 03" src="https://user-images.githubusercontent.com/1078546/163228692-68810448-0038-4052-906b-93d61126a7dc.png">
<img width="1668" alt="Screenshot 2022-04-13 at 17 34 44" src="https://user-images.githubusercontent.com/1078546/163228696-d381e232-7607-4fb2-be04-e5523c6a5159.png">
<img width="1782" alt="Screenshot 2022-04-13 at 17 33 59" src="https://user-images.githubusercontent.com/1078546/163228699-aa771360-d43c-462a-97f7-ea3890c4786d.png">

**Comment by marianogappa** [comment]
Btw, the experiment I described above wouldn't work because the README code doesn't have a validator middleware. I added these middlewares and it still doesn't fail:

```
	s.Use(
		gzip.Middleware, // Response compression with support for direct gzip pass through.
		request.ValidatorMiddleware(validatorFactory),
		request.DecoderMiddleware(decoderFactory),
		request.ValidatorMiddleware(validatorFactory),
		restResponse.EncoderMiddleware,
	)
```

**Comment by vearutop** [comment]
That's an interesting finding, if you use `json` body
```go
	type helloInput struct {
		Locale string   `json:"locale" default:"en-US" pattern:"^[a-z]{2}-[A-Z]{2}$" enum:"ru-RU,en-US"`
		Name   string   `path:"name" minLength:"3"` // Field tags define parameter location and JSON schema constraints.
		_      struct{} `additionalProperties:"false"`
	}
....
	s.Post("/hello/{name}", u)
```

then it works as expected

```
curl -X 'POST'   'http://localhost:8011/hello/Jane'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
  "locale": "en-US", "foo":"bar"
}'
{"status":"INVALID_ARGUMENT","error":"invalid argument: validation failed","context":{"body":["#: additionalProperties \"foo\" not allowed"]}}
```

However, for URL/header parameters OpenAPI [does not have](https://github.com/OAI/OpenAPI-Specification/issues/2511) a concept of disallowed unknown parameters. This library works closely with OpenAPI standard, that's why validation passed for unknown query params.

I'll add special special check to support this case, thank you for raising concern.

> Btw, the experiment I described above wouldn't work because the README code doesn't have a validator middleware.

Request validator middleware is included in [`web.DefaultService()`](https://github.com/swaggest/rest/blob/v0.2.25/web/service.go#L39) facade to simplify initialization for common case.

**Comment by vearutop** [comment]
Please try `v0.2.26`, now unknown non-body parameters should also respect `additionalProperties:"false"`.
Though there is and additional configuration requirement to mention parameter location in field tag, e.g. `query:"_"`.

```go
	type helloInput struct {
		Locale string `query:"locale" default:"en-US" pattern:"^[a-z]{2}-[A-Z]{2}$" enum:"ru-RU,en-US"`
		Name   string `path:"name" minLength:"3"` // Field tags define parameter location and JSON schema constraints.

		// Field tags of unnamed fields are applied to parent schema.
		// they are optional and can be used to disallow unknown parameters.
		// For non-body params, name tag must be provided explicitly.
		// E.g. here no unknown `query` and `cookie` parameters allowed,
		// unknown `header` params are ok.
		_ struct{} `query:"_" cookie:"_" additionalProperties:"false"`
	}
```

This additional requirement is introduced to allow more granular control, for example you may want to forbid unknown `query` parameters, but it is not practical to forbid unknown `header` parameters.

Please reopen this issue if the problem persists.

**Comment by marianogappa** [comment]
@vearutop I've just confirmed this solution works well 👍 Thank you!
